name: Telegram Ping Raw

on:
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Raw POST to Telegram
        env:
          TG_TOKEN  : ${{ secrets.TG_TOKEN }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
        run: |
          set -x
          curl -sS -X POST \
            --data-urlencode "chat_id=${TG_CHAT_ID}" \
            --data-urlencode "text=🔔 Prueba *RAW* desde GitHub (UTC $(date -u +%H:%M))" \
            --data-urlencode "parse_mode=Markdown" \
            "https://api.telegram.org/bot${TG_TOKEN}/sendMessage" \
            | jq .
