name: Test Telegram

on:
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      # 1) Traer el código del repo
      - uses: actions/checkout@v4

      # 2) Instalar Python y dependencias mínimas
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install deps
        run: pip install -r requirements.txt

      # 3) Crear un jobs_latest.json ficticio + llamar al sender
      - name: Send test message
        env:
          TG_TOKEN  : ${{ secrets.TG_TOKEN }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
        run: |
          echo '[{"title":"Ping manual","company":"Pipeline","city":"Here","description":"Prueba desde GitHub","url":"https://example.com"}]' > jobs_latest.json
          python -m notify.push
